spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/tea_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&&serverTimezone=UTC
    username: root
#    password: bbbbbblackfree
    password: Aa@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      max-lifetime: 120000
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    host: smtp.qq.com
    username: 1370441324@qq.com
    password: jbsdymeewtogjdgh
    properties:
      mail:
        smtp:
          port: 465
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    default-encoding: utf-8
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  #  windows中的图片路径
  real-path: D:/DataBase/pictures/
  #  linux中的图片路径
  #  real-path: /usr/projects/compus/picture/
  vir-path: /file/
#logging:
#  level:
#    root: debug